---
- hosts: all
  sudo: yes
  tasks:
    - name: Set hostname to FQDN
      hostname:
        name: "{{ ansible_hostname }}.{{ fqdn }}"
    - name: Fix up /etc/hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}.{{ fqdn }}"
        create: yes
    - name: Install NetworkManager
      yum:
        name: NetworkManager
        state: present
    - name: Enable and restart NetworkManager
      service:
        name: NetworkManager
        state: restarted
        enabled: yes
